version: '3.7'

services:
  ui-app:
    build: ./ui
    restart: always
    ports:
      - '3000:80'
    links:
      - api-app

  api-app:
    build: ./api
    restart: always
    ports:
      - '4000:4000'
